query ProductList(
  $first: Int!
  $channel: String!
  $filter: ProductFilterInput
  $sortBy: ProductOrder
) {
  products(first: $first, channel: $channel, filter: $filter, sortBy: $sortBy) {
    totalCount
    edges {
      node {
        id
        name
        slug
        thumbnail {
          url
          alt
        }
        pricing {
          priceRange {
            start {
              gross {
                amount
                currency
              }
            }
          }
        }
      }
    }
  }
}

query ProductCategories {
  categories(first: 100) {
    edges {
      node {
        id
        name
        slug
      }
    }
  }
}
