query ProductDetail($slug: String!, $channel: String!) {
  product(slug: $slug, channel: $channel) {
    id
    name
    description
    rating
    category {
      id
      name
      slug
    }
    thumbnail {
      url
      alt
    }
    media {
      id
      url
      alt
      sortOrder
      type
    }
    reviewsMetadata: metafield(key: "reviews")
    bundleComponents: metafield(key: "bundle_components")
    variants {
      id
      name
      quantityAvailable
      pricing {
        price {
          gross {
            amount
            currency
          }
        }
      }
    }
  }
}
