fragment ProductCardFields on Product {
  id
  name
  slug
  rating
  featured: metafield(key: "featured")
  thumbnail {
    url
    alt
  }
  pricing {
    priceRange {
      start {
        gross {
          amount
          currency
        }
      }
    }
  }
  variants {
    quantityAvailable
  }
}

query ProductList(
  $first: Int!
  $channel: String!
  $filter: ProductFilterInput
  $sortBy: ProductOrder
) {
  products(first: $first, channel: $channel, filter: $filter, sortBy: $sortBy) {
    totalCount
    edges {
      node {
        ...ProductCardFields
      }
    }
  }
}

query ProductCategories($channel: String!) {
  categories(first: 100) {
    edges {
      node {
        id
        name
        slug
        parent {
          id
        }
        products(channel: $channel) {
          totalCount
        }
        children(first: 20) {
          edges {
            node {
              id
              name
              slug
              products(channel: $channel) {
                totalCount
              }
            }
          }
        }
      }
    }
  }
}
